var usersJson = function () {
    return {
        users: [{
            id: 1,
            name: 'Justyna',
            surname: 'Mrzygłocka',
            born: '1992-01-30',
            nameDate: '',
            imgSrc: 'jm1992.jpg'
        }, {
            id: 2,
            name: 'Zygmunt',
            surname: 'Mrzygłocki',
            born: '1954-10-02',
            nameDate: '',
            imgSrc: 'zm1954.jpg'
        }, {
            id: 3,
            name: 'Regina',
            surname: 'Mrzygłocka',
            born: '1955-01-12',
            nameDate: '',
            imgSrc: 'rm1955.jpg'
        }, {
            id: 4,
            name: 'Wioletta',
            surname: 'Szatkiewicz',
            born: '1968-12-17',
            nameDate: '1968-10-29',
            imgSrc: 'wsz1968.JPG'
        }, {
            id: 5,
            name: 'Tomasz',
            surname: 'Szatkiewicz',
            born: '1967-06-05',
            nameDate: '1967-09-22',
            imgSrc: 'ts1967.jpg'
        }, {
            id: 6,
            name: 'Kacper',
            surname: 'Mrzygłocki',
            born: '2012-01-07',
            nameDate: '',
            imgSrc: ''
        }, {
            id: 7,
            name: 'Krystian',
            surname: 'Szatkiewicz',
            born: '1993-08-22',
            nameDate: '1993-12-04',
            imgSrc: 'ks1993.JPG'
        }, {
            id: 8,
            name: 'Łukasz',
            surname: 'Wiśniewski',
            born: '1993-08-04',
            nameDate: '',
            imgSrc: 'łw1993.JPG'
        }, {
            id: 9,
            name: 'Asia',
            surname: 'Mrzygłocka',
            born: '1979-11-29',
            nameDate: '',
            imgSrc: 'am1979.jpg'
        }, {
            id: 10,
            name: 'Emilia',
            surname: 'Mrzygłocka',
            born: '2011-01-10',
            nameDate: '',
            imgSrc: 'em2011.jpg'
        }, {
            id: 11,
            name: 'Kasia',
            surname: 'Mrzygłocka',
            born: '2006-02-16',
            nameDate: '',
            imgSrc: 'km2006.jpg'
        }, {
            id: 12,
            name: 'Gosia',
            surname: 'Mrzygłocka',
            born: '2008-12-11',
            nameDate: '',
            imgSrc: 'gm2008.jpg'
        }, {
            id: 13,
            name: 'Monika',
            surname: 'Mrzygłocka',
            born: '1984-04-23',
            nameDate: '',
            imgSrc: 'mm1984.jpg'
        }, {
            id: 14,
            name: 'Asia',
            surname: 'Mrzygłocka-Dopke',
            born: '1991-02-08',
            nameDate: '',
            imgSrc: 'amd1991.jpg'
        }, {
            id: 15,
            name: 'Milena',
            surname: 'Mrzygłocka',
            born: '2016-09-25',
            nameDate: '',
            imgSrc: ''
        }, {
            id: 16,
            name: 'Tomasz',
            surname: 'Mrzygłocki',
            born: '1979-12-23',
            nameDate: '',
            imgSrc: ''
        }, {
            id: 17,
            name: 'Andrzej',
            surname: 'Maciąg',
            born: '1943-02-13',
            nameDate: '1943-11-30',
            imgSrc: 'am1943.JPG'
        }, {
            id: 18,
            name: 'Teresa',
            surname: 'Maciąg',
            born: '1947-07-08',
            nameDate: '1947-10-15',
            imgSrc: 'tm1947.JPG'
        }, {
            id: 19,
            name: 'Pusia',
            surname: 'Szatkiewicz-Maciąg',
            born: '2005-08-21',
            nameDate: '',
            imgSrc: 'psm2005.JPG'
        }, {
            id: 20,
            name: 'Bubina',
            surname: 'Mrzygłocka-Szatkiewicz',
            born: '2016-01-31',
            nameDate: '',
            imgSrc: 'bms2016.jpg'
        }, {
            id: 21,
            name: 'Dorota',
            surname: 'Zapolska',
            born: '1991-09-20',
            nameDate: '',
            imgSrc: 'dz1991.jpg'
        }, {
            id: 22,
            name: 'Marika',
            surname: 'Witkowska',
            born: '1998-09-25',
            nameDate: '',
            imgSrc: 'mw1998.jpg'
        }, {
            id: 23,
            name: 'Żaneta',
            surname: 'Lewicka',
            born: '1994-08-20',
            nameDate: '',
            imgSrc: 'żl1994.jpg'
        }, {
            id: 24,
            name: 'Sandra',
            surname: 'Maciąg',
            born: '1998-11-30',
            nameDate: '',
            imgSrc: 'sm1998.jpg'
        }, {
            id: 25,
            name: 'Radek',
            surname: 'Mierzejewski',
            born: '1993-03-29',
            nameDate: '',
            imgSrc: 'rm1993.jpg'
        }, {
            id: 26,
            name: 'Patryk',
            surname: 'Piotrowicz',
            born: '1993-05-04',
            nameDate: '',
            imgSrc: 'pp1993.jpg'
        }, {
            id: 27,
            name: 'Dominik',
            surname: 'Szulc',
            born: '1989-12-02',
            nameDate: '',
            imgSrc: 'ds1989.jpg'
        }, {
            id: 28,
            name: 'Milena',
            surname: 'Witkowska',
            born: '1978-02-18',
            nameDate: '',
            imgSrc: 'mw1978.JPG'
        }, {
            id: 29,
            name: 'Mateusz',
            surname: 'Lewicki',
            born: '1992-10-17',
            nameDate: '',
            imgSrc: 'ml1992.jpg'
        }, {
            id: 30,
            name: 'Szymon',
            surname: 'Witkowski',
            born: '2000-06-28',
            nameDate: '2000-07-01',
            imgSrc: 'sw2000.JPG'
        }, {
            id: 31,
            name: 'Marek',
            surname: 'Maciąg',
            born: '1971-10-15',
            nameDate: '1971-11-22',
            imgSrc: 'mm1971.JPG'
        }, {
            id: 32,
            name: 'Jadwiga',
            surname: 'Szatkiewicz',
            born: '1943-12-26',
            nameDate: '1943-10-15',
            imgSrc: ''
        }, {
            id: 33,
            name: 'Sławek',
            surname: 'Szatkiewicz',
            born: '1975-07-29',
            nameDate: '1975-11-05',
            imgSrc: 'ssz1975.jpg'
        }, {
            id: 34,
            name: 'Aneta',
            surname: 'Jurkiewicz',
            born: '1978-12-23',
            nameDate: '',
            imgSrc: 'aj1978.jpg'
        }, {
            id: 35,
            name: 'Bianka',
            surname: 'Szatkiewicz',
            born: '2012-09-04',
            nameDate: '',
            imgSrc: 'bsz2012.jpg'
        }, {
            id: 36,
            name: 'Aleksander',
            surname: 'Jeszke',
            born: '1978-01-27',
            nameDate: '',
            imgSrc: 'aje1978.jpg'
        }, {
            id: 37,
            name: 'Arek',
            surname: 'Richert',
            born: '1988-03-04',
            nameDate: '',
            imgSrc: 'ar1988.jpg'
        }, {
            id: 38,
            name: 'Małgorzata',
            surname: 'Wendt',
            born: '1992-08-13',
            nameDate: '',
            imgSrc: 'mw1992.jpg'
        }, {
            id: 39,
            name: 'Grzegorz',
            surname: 'Mrzygłocki',
            born: '1984-03-20',
            nameDate: '',
            imgSrc: 'gm1984.jpg'
        }]
    };
};
