var usersJson = function () {
    return {
        users: [{
            name: 'Justyna',
            surname: 'Mrzygłocka',
            born: '1992-01-30',
            nameDate: '',
            imgSrc: 'jm1992.jpg'
        }, {
            name: 'Zygmunt',
            surname: 'Mrzygłocki',
            born: '1954-10-02',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Regina',
            surname: 'Mrzygłocka',
            born: '1955-01-12',
            nameDate: '',
            imgSrc: 'rm1955.jpg'
        }, {
            name: 'Wioletta',
            surname: 'Szatkiewicz',
            born: '1968-12-17',
            nameDate: '1968-10-29',
            imgSrc: 'wsz1968.JPG'
        }, {
            name: 'Tomasz',
            surname: 'Szatkiewicz',
            born: '1967-06-05',
            nameDate: '1967-09-22',
            imgSrc: 'ts1967.jpg'
        }, {
            name: 'Kacper',
            surname: 'Mrzygłocki',
            born: '2012-01-07',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Krystian',
            surname: 'Szatkiewicz',
            born: '1993-08-22',
            nameDate: '1993-12-04',
            imgSrc: 'ks1993.JPG'
        }, {
            name: 'Łukasz',
            surname: 'Wiśniewski',
            born: '1993-08-04',
            nameDate: '',
            imgSrc: 'łw1993.JPG'
        }, {
            name: 'Asia',
            surname: 'Mrzygłocka',
            born: '1979-11-29',
            nameDate: '',
            imgSrc: 'am1979.jpg'
        }, {
            name: 'Emilia',
            surname: 'Mrzygłocka',
            born: '2011-01-10',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Kasia',
            surname: 'Mrzygłocka',
            born: '2006-02-16',
            nameDate: '',
            imgSrc: 'km2006.jpg'
        }, {
            name: 'Gosia',
            surname: 'Mrzygłocka',
            born: '2008-12-11',
            nameDate: '',
            imgSrc: 'gm2008.jpg'
        }, {
            name: 'Monika',
            surname: 'Mrzygłocka',
            born: '1984-04-23',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Asia',
            surname: 'Mrzygłocka-Dopke',
            born: '1991-02-08',
            nameDate: '',
            imgSrc: 'amd1991.jpg'
        }, {
            name: 'Milena',
            surname: 'Mrzygłocka',
            born: '2016-09-25',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Tomasz',
            surname: 'Mrzygłocki',
            born: '1979-12-23',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Andrzej',
            surname: 'Maciąg',
            born: '1943-02-13',
            nameDate: '1943-11-30',
            imgSrc: 'am1943.JPG'
        }, {
            name: 'Teresa',
            surname: 'Maciąg',
            born: '1947-07-08',
            nameDate: '1947-10-15',
            imgSrc: 'tm1947.JPG'
        }, {
            name: 'Pusia',
            surname: 'Szatkiewicz-Maciąg',
            born: '2005-08-21',
            nameDate: '',
            imgSrc: 'psm2005.JPG'
        }, {
            name: 'Bubina',
            surname: 'Mrzygłocka-Szatkiewicz',
            born: '2016-01-31',
            nameDate: '',
            imgSrc: 'bms2016.jpg'
        }, {
            name: 'Dorota',
            surname: 'Zapolska',
            born: '1991-09-20',
            nameDate: '',
            imgSrc: 'dz1991.jpg'
        }, {
            name: 'Marika',
            surname: 'Witkowska',
            born: '1998-09-25',
            nameDate: '',
            imgSrc: 'mw1998.jpg'
        }, {
            name: 'Żaneta',
            surname: 'Lewicka',
            born: '1994-08-20',
            nameDate: '',
            imgSrc: 'żl1994.jpg'
        }, {
            name: 'Sandra',
            surname: 'Maciąg',
            born: '1998-11-30',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Radek',
            surname: 'Mierzejewski',
            born: '1993-03-29',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Patryk',
            surname: 'Piotrowicz',
            born: '1993-05-04',
            nameDate: '',
            imgSrc: 'pp1993.jpg'
        }, {
            name: 'Dominik',
            surname: 'Szulc',
            born: '1989-12-02',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Milena',
            surname: 'Witkowska',
            born: '1978-02-18',
            nameDate: '',
            imgSrc: 'mw1978.JPG'
        }, {
            name: 'Mateusz',
            surname: 'Lewicki',
            born: '1992-10-17',
            nameDate: '',
            imgSrc: ''
        }, {
            name: 'Szymon',
            surname: 'Witkowski',
            born: '2000-06-28',
            nameDate: '2000-07-01',
            imgSrc: 'sw2000.JPG'
        }, {
            name: 'Marek',
            surname: 'Maciąg',
            born: '1971-10-15',
            nameDate: '1971-11-22',
            imgSrc: 'mm1971.JPG'
        }, {
            name: 'Jadwiga',
            surname: 'Szatkiewicz',
            born: '1943-12-26',
            nameDate: '1943-10-15',
            imgSrc: ''
        }]
    };
};